[package]
name = "barq-common"
version = "0.0.1"
edition = "2021"


[dependencies]
# General dependencies
serde = { workspace = true }
anyhow = { workspace = true }

# Dependencies to visualize the graph
petgraph = "0.6"
